#!/bin/bash

#
# Run this in ai/bin/00bin-o
#
if [ ! -x UltimateTicTacToeServer ]; then
    echo "UltimateTicTacToeServer is missing"
    exit 1
fi
if [ ! -x UltimateTicTacToeDisplay ]; then
    echo "UltimateTicTacToeDisplay is missing"
    exit 1
fi
if [ ! -x UltimateTicTacToeAgent ]; then
    echo "UltimateTicTacToeAgent is missing"
    exit 1
fi

# Launch the game server
./UltimateTicTacToeServer -S 5 -d 0 -s 100 -a 2 -T 1 -R 1 >server.log 2>server.err &
echo "Waiting for server to get started"
sleep 2

# Launch the display
./UltimateTicTacToeDisplay >display.log 2>display.err &

# Launch random as first player
./UltimateTicTacToeAgent -a r -t 0 >agent1.log 2>agent1.err &

# Launch random as second player
./UltimateTicTacToeAgent -a r -t 0 >agent2.log 2>agent2.err &



